### ISSUE TITLE
Epic: Extending Schema2Graph capabilities

### ISSUE THREAD

**Issue by rofrano** [konveyor/tackle-data-gravity-insights#61]
**As a** Application Architect
**I need** the ability to analyze constraints, triggers, and other schema artifacts
**So that** I get a complete picture of the relationships between tables

### Details & Assumptions

This list will be finalized when #58 exploration is complete:

- [ ] Add constraints to the graph to show how some columns are being used
- [ ] Add indexes to the graph to indicate columns used in queries
- [ ] Add triggers and field procedures to the graph to understand how updating columns affect other columns
- [ ] Add stored procedures to the graph
